WebExsel/WebExsel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

WebExsel/main/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import DocumentAPIView

app_name = "main"

urlpatterns = [
    path("", views.uploadFile, name="uploadFile"),
    path("api/v1/documentlist", DocumentAPIView.as_view())
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

WebExsel/main/models.py
from django.db import models


class Document(models.Model):
    title = models.CharField(max_length=200)
    uploadedFile = models.FileField(upload_to="Uploaded Files/")
    dateTimeOfUpload = models.DateTimeField(auto_now=True)
    databasename1 = models.FileField(upload_to="Uploaded Files/")

WebExsel/main/views.py
from django.shortcuts import render
from . import models
from rest_framework import generics
from .models import Document
from .serializers import DocumentSerializer
import os
import sqlite3
import openpyxl


def uploadFile(request):
    if request.method == "POST":
        # Fetching the form data
        fileTitle = request.POST["fileTitle"]
        uploadedFile = request.FILES["uploadedFile"]

        databasename1 = request.POST["fileTitle"] + 'exsel_database1.db'
        # Saving the information in the database
        document = models.Document(
            title=fileTitle,
            uploadedFile=uploadedFile,
            databasename1=databasename1
        )
        document.save()
        # метод sqlite3.connect автоматически создаст базу, если ее нет

        connect = sqlite3.connect(f'C:/Users/PopSmokePurpp/PycharmProjects/Django_B1/WebExsel/media/Uploaded Files/{fileTitle}exsel_datadase1.db')
        # курсор - это специальный объект, который делает запросы и получает результаты запросов
        cursor = connect.cursor()
        cursor.execute(
            '''CREATE TABLE IF NOT EXISTS tab_1([_id] integer PRIMARY KEY AUTOINCREMENT,
            [bankacc] int,
            [saldo_vxod_aktiv] int,
            [saldo_vxod_pasiv] int,
            [oboroti_debet] int,
            [oboroti_kredit] int,
            [saldo_ishod_aktiv] int,
            [saldo_oshod_pasiv] int)
            ''')

        file_to_read = openpyxl.load_workbook(uploadedFile, data_only=True)
        sheet = file_to_read['Sheet1']
        for row in range(7, 636):
            # Объявление списка
            data = []
            # Цикл по столбцам от 1 до 4 ( 5 не включая)
            for col in range(1, 8):
                # value содержит значение ячейки с координатами row col
                value = sheet.cell(row, col).value
                # Список который мы потом будем добавлять
                data.append(value)

            # Вставка данных в поля таблицы
            cursor.execute(
                "INSERT INTO tab_1(bankacc, saldo_vxod_aktiv,"
                " saldo_vxod_pasiv, oboroti_debet, oboroti_kredit,"
                " saldo_ishod_aktiv, saldo_oshod_pasiv)"
                " VALUES (?, ?, ?, ?, ?, ?, ?);",
                (data[0], data[1], data[2], data[3], data[4], data[5], data[6]))

        # сохраняем изменения
        connect.commit()
        # закрытие соединения
        connect.close()

    documents = models.Document.objects.all()

    return render(request, "main/upload-file.html", context={
        "files": documents
    })


class DocumentAPIView(generics.ListAPIView):
    queryset = Document.objects.all()
    serializer_class = DocumentSerializer

WebExsel/main/templates/main/upload-file.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django File Upload</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');

        * {
            font-family: "Roboto";
        }

        body {
            background-color: #F5F5F5;
        }

        form {
            background-color: #FFFFFF;
            padding: 25px;
        }

        table {
            width: 100%;
            text-align: center;
            margin-top: 25px;
            padding: 25px;
            background-color: #FFFFFF;
        }

        table tr td {
            padding-top: 15px;
        }
    </style>
</head>
<body>
    <form action="{% url 'main:uploadFile' %}" method="POST" enctype="multipart/form-data">
        <input type="text" name="fileTitle" placeholder="Enter a title">
        <input type="file" name="uploadedFile">
        {% csrf_token %}
        <input type="submit" value="Upload">
    </form>
    <table>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>File Path</th>
            <th>Upload Date & Time</th>
            <th>Download file</th>
            <th>Database file</th>
        </tr>
        {% for file in files %}
            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.title }}</td>
                <td>{{ file.uploadedFile.url }}</td>
                <td>{{ file.dateTimeOfUpload }}</td>
                <td>
                <a href="{{ file.uploadedFile.url }}" download="" class="btn btn-success btn-lg">Download</a>
                </td>
                <td>
                    <a href="{{ file.databasename1.url }}" download="" class="btn btn-success btn-lg">{{ file.databasename1 }}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>